# Generated by Django 3.2.7 on 2021-10-01 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deploy_time', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
                ('title_image', models.ImageField(blank=True, default=None, null=True, upload_to='articles/')),
                ('text', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['author', '-deploy_time'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('profile_photo', models.ImageField(blank=True, default=None, null=True, upload_to='profiles/')),
            ],
            options={
                'ordering': ['-username'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('deploy_time', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.FileField(blank=True, default=None, null=True, upload_to='attachments/')),
                ('article_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum_app.article')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum_app.user')),
                ('comment_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum_app.comment')),
            ],
            options={
                'ordering': ['article_parent', 'comment_parent', '-deploy_time'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum_app.user'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('V', 'View'), ('L', 'Like'), ('D', 'Dislike')], max_length=1)),
                ('article_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum_app.article')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum_app.user')),
                ('comment_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum_app.comment')),
            ],
            options={
                'ordering': ['author', '-activity_type'],
                'unique_together': {('author', 'article_parent', 'comment_parent', 'activity_type')},
            },
        ),
    ]
